#Amazon AWS Config
development:
  access_key_id: AKIAJ6LZX5LFVVBVACAQ
  secret_access_key: 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
  bucket: unicloudstorage
 
production:
  access_key_id: AKIAJ6LZX5LFVVBVACAQ
  secret_access_key: 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
  bucket: unicloudstorage