#Amazon AWS Config
development: &development
  access_key_id: ENV['access_key_id']
  secret_access_key: ENV['secret_access_key']
  bucket: ENV['bucket']
  dynamo_db_endpoint:  ENV['dynamo_db_endpoint']
 
production:
  access_key_id: ENV['access_key_id']
  secret_access_key: ENV['secret_access_key']
  bucket: ENV['bucket']
  dynamo_db_endpoint:  ENV['dynamo_db_endpoint']
  
test:
  <<: *development